#  environment document

name: mriland
channels:
  - conda-forge
  
dependencies:
  - python=3.8.6
  - imageio=2.25.0
  - jupyter=1.0.0
  - matplotlib=3.3.3
  - nest-asyncio=1.5.5
  - notebook=6.4.10
  - numexpr=2.7.3
  - numpy=1.22.3
  - pandas
  - scipy=1.7.3
  - scikit-image=0.19.2
  - jupyterlab=3.6.1
  - ipympl=0.9.3


